### ISSUE TITLE
Pain points with "View Query"

### ISSUE THREAD

**Issue by g-may** [watson-developer-cloud/discovery-nodejs#38]
- Queries for each insight pane (Top Stories, Top Entities, etc) are all the same, but the responses are different.
 - It is difficult to understand how to construct an API request from the queries.
 - Query should be called "Request", because in the Query pane there is a field called "query"

Right now:
 - Demo makes a single API call and uses sections of the response for different insights
 - "View Query" Query tab is identical for each pane 
 - Response tab is different for each pane

![image](https://media.github.ibm.com/user/2958/files/509cc1d2-5a54-11e7-9a05-df3e4b896e12)

![image](https://media.github.ibm.com/user/2958/files/660aefee-5a54-11e7-9c02-fb1008b37521)

What should happen:
 - Separate requests for each pane to facilitate easy understanding. When someone views the request for the Top Entities pane, they should learn how to get Top Entities alone, not Top Entities, Concepts, Sentiment, etc. 
 - Or the app should more clearly explain that the response in each section is a subset of the single large response
 - "View Query" button and "Query" tab should be called "View Request" / "Request", because Discovery has a specific parameter called "query" that is shown in the "Query" tab

**Comment by maniax89** [comment]
should be fixed by https://github.com/watson-developer-cloud/discovery-nodejs/pull/57
