### ISSUE TITLE
Change titles for consistency

### ISSUE THREAD

**Issue by ghost** [watson-developer-cloud/discovery-nodejs#6]
The hosted demo is at a URL that contains: discovery-news-demo.

Let's change the repo name to: watson-developer-cloud/discovery-news-demo.

And change the main readme title to: "Discovery News Demo".

**Comment by germanattanasio** [comment]
We use `discovery-nodejs` because we have some services implementing the same UI but with a different backend. `personality-insights-java` or `personality-insights-python` are one example. Adding `demo` to this repo will break that pattern which users are used to.

**Comment by ghost** [comment]
@germanattanasio 
What about
https://github.com/watson-developer-cloud/raspberry-pi-time-weather-demo
and
https://github.com/watson-developer-cloud/arduino-pi-badge-demo
?

At the very least, we would want to specify that this is for News, to distinguish from other Discovery technical assets

**Comment by germanattanasio** [comment]
@jscherping the README has a pretty big gif where you can see what the app looks like. We can update the README but changing the repository name it's a pretty big change and I don't think we have data saying that the current name is wrong/confusing.
