### ISSUE TITLE
Trying to Deploy on BlueMix by Pressing button on ReadMe fails with the following errors

### ISSUE THREAD

**Issue by jdellaria** [watson-developer-cloud/discovery-nodejs#80]
By pressing the "Deploy to Bluemix" button in the readme and making no changes to the code. The following is my log file.

Also  REACT_APP_BLUEMIX_ANALYICS: is not in my manifest.yml file, but DEMO_DEPLOY apprears to be in it place.

My intention is to get this to run on one of my Discovery collections... Does the discovery collection have to be a standard collection?

Thanks in advance for the Feedback.

Jon
--------------------------------------------------------------- Log file
Preparing to start the job...
Preparing the build artifacts...
Target: https://api.ng.bluemix.net
FAILED
Service instance Discovery-Demo not found
Creating service instance Discovery-Demo in org jdellaria@us.ibm.com / space dev as jdellaria@us.ibm.com...
OK

Create in progress. Use 'cf services' or 'cf service Discovery-Demo' to check operation status.

Attention: The plan `standard` of service `discovery` is not free.  The instance `Discovery-Demo` will incur a cost.  Contact your administrator if you think this is in error.

Writing manifest.yml...
Manifest file written
name: watson-discovery-service-news-demo-JonD-1
instances: 5
memory: 512M
command: node server.js
services:
  - Discovery-Demo
env:
  REACT_APP_BLUEMIX_ANALYICS: 

Pushing new app:watson-discovery-service-news-demo-JonD-1
FAILED
Error reading manifest file:
env var 'REACT_APP_BLUEMIX_ANALYICS' should not be null

Finished: FAILED
-------

**Comment by maniax89** [comment]
could you check to see if it works now? should be fixed by #81

**Comment by jdellaria** [comment]
This solved the problem. Thank you!

Jon Dellaria
