### ISSUE TITLE
Not Authorized error When searching in discovery-nodejs from localhost

### ISSUE THREAD

**Issue by jdellaria** [watson-developer-cloud/discovery-nodejs#82]
When following the instructions in the readme file to Run the demo locally I am I am getting a "Not Authorized" error.. I have created my discovery service and have all the associated password and logins in the .env file

![screenshot 2017-11-14 13 41 46](https://user-images.githubusercontent.com/22420233/32798157-de2fb39a-c941-11e7-8b15-cca873e90a7a.jpg)

**Comment by pegomez** [comment]
Good morning @jdellaria.
Exactly the same the problem when I launched it for the first time. I strongly believe it is something related with the `app.js` file. Take a look at this part:

`const discovery = new DiscoveryV1({ 
  // If unspecified here, the DISCOVERY_USERNAME and
  // DISCOVERY_PASSWORD env properties will be checked
  // After that, the SDK will fall back to the bluemix-provided VCAP_SERVICES environment property
  username: 'XXXXXXXXXXX',
  password: 'YYYYYYYYYYY',
  version_date: '2017-11-07',
});`
* please take also into account the fact that no <> or {} should be before and after the username and password.

Replace the XXX and YYY by your own credentials. It worked for me. Also, replace the `.env.example` file with your own data. It is Laravel related, but as I keep it updated it still work.

I hope your app is up and running soon.
Best regards :-)

**Comment by germanattanasio** [comment]
As @pegomez said, you need to use your credentials in order to run the demo.
See https://github.com/watson-developer-cloud/discovery-nodejs#setup-a-ibm-watson-discovery-service
