### ISSUE TITLE
Odd behavior when loading the demo from various sites

### ISSUE THREAD

**Issue by Mikemosca** [watson-developer-cloud/discovery-nodejs#93]
**Behavior:**
Not 100% reproducible.  You have have to try a few times.

https://discovery-news-demo.ng.bluemix.net/

Sometimes the Discovery demo does not load properly or does not load at all from various sites like the watson console or marketing pages.

## Steps for Reproducing

1. https://console.bluemix.net/developer/watson/services - click on Discovery **Demo** link
2. https://www.ibm.com/watson/services/discovery/ - click on **View deno** button
3.

## Screenshots

<img width="978" alt="screen shot 2018-04-20 at 12 40 43 pm" src="https://user-images.githubusercontent.com/20446629/39064094-37795d00-449b-11e8-9f69-dc4fa356e44b.png">

**Comment by maniax89** [comment]
@Mikemosca I think I just fixed the issue - we had 2 deployments for the same URL, so things were getting funky

please close the issue if you no longer experience the weird behavior

**Comment by Mikemosca** [comment]
Yea, That's better!
